### ISSUE TITLE
Logging Configurations

### ISSUE THREAD

**Issue by mlavin** [caktus/django-project-template#38]
The default project should use common location/formats for logging. This includes the project itself as well as the services like Gunicorn and Nginx. If we send the logs to syslog then it should be easy to push them to a remote server with rsyslog.

**Comment by dpoirier** [comment]
It would also be nice if when something goes wrong, the development team's inboxes weren't crushed under a flood of emails from the Django logging system. Sometimes the volume can be so large that log emails are still trickling in 24 hours after the problem is fixed.

I suspect this means routing the log messages to some system that will watch for problems and send an alert when a problem starts, instead of at every error reported. But there might be other solutions... maybe someone has written a Python log handler that can do something similar without needing another system. It's worth investigating.

**Comment by dpoirier** [comment]
In terms of being notified about exceptions without being flooded by emails, using Sentry might be a good option. It seems to work okay for the Pycon servers.

**Comment by mlavin** [comment]
There have been a number of improvements in this area. I'm going to close this. Future improvements can be tracked in their own issues.
